result_path: 'results'
start_gen: 0
iter_num: 100
sim_num: 1
sephist_step: 1
consensus_dist: False
track_fitness: False
fixed_popsize: 'all_groups'
fixed_params:
  init_n: 500
  x_threshold: 0.05
  k: 4
  lim_speakers: 1
  lim_listeners: 30
  ng: 1
  mu_rate: 0.01
  alpha_var: 0.0025
  K: 50
  ra: 0.1
  gammar: 0.05
  betar: 5
  gammab: 0.005
  betab: 5000
  S: 0
  b_mid: 100
  Ct: 3
  q: 0.1
  m: 0.05
  dr: 0.1
  criterion: 'sd_threshold'
  init_cond: 'right_skew'
  lead_type: 'persuasive'
  lead_clust: False